plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
    id 'com.bmuschko.docker-java-application'
    id 'com.avast.gradle.docker-compose' version '0.17.0'
}

group = 'org.octopusden.octopus'


java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	// Spring Boot starters
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-cache'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'

	// Database
	runtimeOnly 'org.postgresql:postgresql'

	// Utilities
	implementation 'commons-io:commons-io:2.20.0'
	implementation 'com.google.code.gson:gson:2.13.1'
	implementation 'com.github.ben-manes.caffeine:caffeine'

    // Maven artifact handling
    implementation 'org.apache.maven:maven-artifact:3.9.11'

    // OpenAPI/Swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.0'

	// Octopus and Keycloak
	implementation 'org.octopusden.octopus.releng:releng-lib:2.0.8'
	implementation 'org.keycloak:keycloak-spring-boot-starter:22.0.2'

	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'junit:junit:4.13.2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

def dockerRegistry = System.getenv().getOrDefault("DOCKER_REGISTRY", project.properties["docker.registry"])
def octopusGithubDockerRegistry = System.getenv().getOrDefault("OCTOPUS_GITHUB_DOCKER_REGISTRY", project.properties["octopus.github.docker.registry"])

dockerCreateDockerfile.doLast {
    copy {
        from 'Dockerfile'
        into dockerSyncBuildContext.destinationDir
    }
}

tasks.named('dockerSyncBuildContext') {
    def bootJarArchive = tasks.named('bootJar').flatMap { it.archiveFile }
    from(bootJarArchive) {
        into('build/libs')
    }
    dependsOn bootJar
}

dockerBuildImage {
    inputDir = dockerSyncBuildContext.destinationDir
    buildArgs.put("DOCKER_REGISTRY", "$dockerRegistry")
    buildArgs.put("BUILD_VERSION", "${project.version}")
    images.set(["$octopusGithubDockerRegistry/octopusden/components-lifecycle-service:${project.version}"])

    dependsOn dockerSyncBuildContext
    dependsOn bootJar
}

dockerCompose {
    dockerExecutable = "/opt/homebrew/bin/docker"
    useComposeFiles = ['docker/tests/docker-compose.yml']
    removeContainers = true       // remove containers after stopping
    removeVolumes = true          // remove volumes after stopping
    isRequiredBy(tasks.test)      // ensures tests run after Compose services are up
    waitForTcpPorts = true        // waits for TCP ports defined in compose healthchecks
}