# Project version
version=1.0.0-SNAPSHOT

# Plugin versions
springBootVersion=3.4.1
dependencyManagementVersion=1.1.7
dockerPluginVersion=9.4.0

# Dependency versions
springCloudVersion=2024.0.0
springdocVersion=2.7.0
octopusSecurityCommonVersion=2.0.16
commonsIoVersion=2.20.0
mavenArtifactVersion=3.9.9
octopusVersionsApiVersion=2.0.10

# Java version
javaVersion=21

# Docker settings
docker.registry=docker.io
octopus.github.docker.registry=${docker.registry}
