services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
      - --import-realm
    ports:
      - "8083:8080"
    volumes:
      - ./realms:/opt/keycloak/data/import
  db:
    image: postgres:15
    container_name: cls-postgres
    restart: always
    environment:
      POSTGRES_DB: cls
      POSTGRES_USER: cls_user
      POSTGRES_PASSWORD: cls_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: