name: Gradle Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  start-services:
    runs-on: ubuntu-latest
    outputs:
      services-ready: true
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose
        run: |
          docker compose -f docker/tests/docker-compose.yml up -d

  run-build-and-deploy:
    needs: start-services
    uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.10
    with:
      flow-type: hybrid
      java-version: '21'
      docker-image: components-lifecycle-service
      skip-tests: false
