name: Gradle Compile & UT

on: [push, pull_request, workflow_dispatch]

jobs:
  run-build-and-deploy-with-services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Start Docker Compose services
        run: |
          docker compose -f docker/tests/docker-compose.yml up -d
          docker compose -f docker/tests/docker-compose.yml exec -T db sh -c \
          "until pg_isready -U postgres; do sleep 1; done"

      - name: Run Gradle build via reusable workflow
        uses: octopusden/octopus-base/.github/workflows/common-java-gradle-build.yml@v2.1.10
        with:
          flow-type: hybrid
          java-version: '21'
          docker-image: components-lifecycle-service
          skip-tests: false

      - name: Stop Docker Compose
        if: always()
        run: docker compose -f docker/tests/docker-compose.yml down
